"""Workflow state for the Order Processing Assistant.

WorkflowState is the shared execution state passed between LangGraph nodes.

Workflow:

User
    │
    ▼
IntentAgent
    │
    ▼
SqlAgent
    │
    ▼
ResponseAgent
"""

from typing import Any

from langgraph.graph import MessagesState

from app.schemas.intent_schema import IntentEnum
from app.schemas.sql_result_schema import QueryResult


class WorkflowState(MessagesState):
    """Shared workflow state for the Order Processing Assistant.

    Every LangGraph node reads from and writes to this shared state.

    Attributes:
        question:
            Original user question.

        intent:
            Business intent detected by the IntentAgent.

        entities:
            Extracted business entities such as customer name, order ID,
            shipment status, date ranges, etc.

        ready_for_sql:
            Whether sufficient information exists to continue with SQL
            generation.

        missing_parameters:
            Parameters that must be collected before SQL generation.

        follow_up_question:
            Clarification question returned by the IntentAgent.

        schema_context:
            Relevant schema metadata retrieved from the Knowledge Base.

        generated_sql:
            SQL retrieved from cache, template repository, or generated by
            the LLM.

        sql_explanation:
            Human-readable explanation of the generated SQL.

        query_result:
            Result returned from executing the SQL statement.

        final_response:
            Business-friendly response generated by the ResponseAgent.

        error_message:
            User-facing error message.
    """

    # ------------------------------------------------------------------
    # User Input
    # ------------------------------------------------------------------

    question: str

    # ------------------------------------------------------------------
    # Intent Agent
    # ------------------------------------------------------------------

    intent: IntentEnum | None = None

    entities: dict[str, Any] | None = None

    ready_for_sql: bool = False

    missing_parameters: list[str] | None = None

    follow_up_question: str | None = None

    # ------------------------------------------------------------------
    # Knowledge Base
    # ------------------------------------------------------------------

    schema_context: str | None = None

    # ------------------------------------------------------------------
    # SQL Agent
    # ------------------------------------------------------------------

    generated_sql: str | None = None

    sql_explanation: str | None = None

    query_result: QueryResult | None = None

    validated_sql: str | None = None

    # ------------------------------------------------------------------
    # Response Agent
    # ------------------------------------------------------------------

    final_response: str | None = None

    # ------------------------------------------------------------------
    # Errors
    # ------------------------------------------------------------------

    error_message: str | None = None
