"""SQL validation tools used by the SQL Agent.

This module exposes LangChain tools for validating dynamically generated SQL.
The tool is a thin wrapper around the application's SQL validator and contains
no business logic.

Responsibilities:

* Validate that generated SQL is a safe read-only SELECT statement.

The tool updates the shared LangGraph ``WorkflowState`` using
``Command(update=...)``.
"""

from __future__ import annotations
from typing_extensions import Annotated

from langchain_core.tools import tool
from langgraph.types import Command
from langchain_core.messages import ToolMessage
from langchain_core.tools import InjectedToolCallId

from app.config.log_config import config as log_config
from app.utils.validators import validate_select_only

logger = log_config.get_logger(__name__)


@tool
def validate_sql(
    generated_sql: str,
    tool_call_id: Annotated[str, InjectedToolCallId],
) -> Command:
    """Validate a generated SQL statement.

    Ensures the SQL is a safe read-only SELECT statement.

    Args:
        generated_sql: SQL generated by the SQL generation tool.

    Returns:
        Command updating the workflow state.
    """
    logger.info("Validating generated SQL.")

    if not generated_sql:
        logger.warning("No SQL available for validation.")

        return Command(
            update={
                "error_message": "No SQL was generated.",
                "messages": [
                    ToolMessage(
                        content="No SQL was generated.",
                        tool_call_id=tool_call_id,
                    )
                ],
            }
        )

    is_valid = validate_select_only(generated_sql)

    if not is_valid:
        logger.warning("Generated SQL failed validation.")

        return Command(
            update={
                "error_message": "Generated query could not be validated.",
                "messages": [
                    ToolMessage(
                        content="SQL validation failed.",
                        tool_call_id=tool_call_id,
                    )
                ],
            }
        )

    logger.info("SQL validation passed.")

    return Command(
        update={
            "validated_sql": generated_sql,
            "error_message": None,
            "messages": [
                ToolMessage(
                    content="SQL validation successful.",
                    tool_call_id=tool_call_id,
                )
            ],
        }
    )
