"""FastAPI chat router.

Exposes the ``POST /api/chat`` endpoint for the Order Processing Assistant.
The router delegates all business logic to ``ChatService`` and contains no
application logic itself.
"""

from fastapi import APIRouter

from app.config.log_config import config as log_config
from app.schemas.requests_schema import ChatRequest
from app.schemas.responses_schema import ChatResponse
from app.services.chat_service import ChatService

logger = log_config.get_logger(__name__)


class ChatRouter:
    """Class-based router for chat requests.

    The router delegates incoming requests to the injected ``ChatService``,
    keeping the API layer lightweight and easy to test.

    Attributes:
        router: FastAPI router exposing the chat endpoint.
    """

    def __init__(self, chat_service: ChatService) -> None:
        """Initialize the chat router.

        Args:
            chat_service: Shared ``ChatService`` instance.
        """
        self._chat_service = chat_service

        self.router = APIRouter(
            prefix="/api",
            tags=["chat"],
        )

        self.router.add_api_route(
            "/chat",
            self.submit_question,
            methods=["POST"],
            response_model=ChatResponse,
        )

    async def submit_question(self, request: ChatRequest) -> ChatResponse:
        """Process a chat request.

        Args:
            request: Validated chat request.

        Returns:
            Chat response generated by the workflow.
        """
        logger.info(
            "POST /api/chat session=%s",
            request.session_uuid,
        )

        return await self._chat_service.ask(request)
